#!/bin/bash --

set -e
self=$0

function prerun_find_problems {
    dir=$1
    shift
    echo $@ | 
    grep -qv -E "^[0-9]+\s((UNKNOWN)|(\w*)\s${dir}/\3)" && exit 1 || exit 0
}

function adduser {
    dir=$1
    shift
    echo $@ | 
    grep -E "^[0-9]+\s(UNKNOWN)" |
    sed -re "s~([0-9]+)\sUNKNOWN\s$dir/(.*)$~\1 \2~g" |
    xargs --no-run-if-empty -n2 sudo adduser --disabled-password --no-create-home --uid
}

function run {
    find $1 -maxdepth 1 -mindepth 1 -type d | 
    grep -vE "/(system)|(lost[+]found)" | 
    xargs -i{} -n1  bash -c "stat --format '%u %U %n' {} | xargs $self --process $process $@" 
}


if test "z$1z" = "z--processz"
then
    process=$2
    shift; shift
    $process "$@"
else
    process=prerun_find_problems
    run $1

    process=adduser
    run $1
fi

