#!/bin/bash

packages=(

  ##admin
  kuser synaptic 
  evtest #input devices
  ##time
  ntp 

  ##tools
  yakuake emacs emacs-goodies-el emacs-goodies-extra-el vim parallel baobab wireshark zenmap strace

  #-cpulimit trickle

  ##media
  get-iplayer lame

  ##document generation
  markdown
  xmlstarlet

  ##mono
  monodevelop
  monodevelop-nunit

  #couch
  libnewtonsoft-json-cil-dev
  couchdb
  #couchapp
  python-pip
  python-dev
  python-yaml

  ##python
  ipython

  ##ocaml
  "ocaml-interp&M"
  "cameleon&M"

  ##dev tools 
  kdiff3

  ##web development
  "sass-elisp&M" "ruby-sass&M"

  ##dev tools — eclipse
  eclipse-jdt eclipse-mercurialeclipse eclipse-cdt eclipse-egit

  ##revision control
  kdesvn subversion
  tortoisehg-nautilus mercurial-git hgview
  easygit git git-cola git-flow git-gui gitk
  rabbitvcs-nautilus
  kdesdk-dolphin-plugins

  ##desktop
  chromium "flashplugin-nonfree&M" plasma-widget-smooth-tasks plasma-widget-fastuserswitch redshift #update-notifier-kde
  "mail-notification&M"

  ##presentation
  "ardesia&M" 
  "istanbul&M" 
  "recordmydesktop&M"

  ##system
  hibernate gdm3

  ##security
  keepassx

  ##firewall
  ufw squid3 squidguard dnsmasq

  ##multi-media codecs etc
  libavcodec-extra-53 libdvdread4 deb-multimedia-keyring

  ##kids

  ###games
  #in get-games

  ###scratch
  scratch
  etoys
  turtleart
  

  ###art
  ##animation 2d
  "synfigstudio&M" "synfig-examples&M" # have installed manualy to /opt
  "tupi&M"
  "gimp-gap&M"
  
  
  ##presentation
  "sozi&M"
)

aptitude install  "${packages[@]}"
