#!/bin/bash

packages=(
  ##games	
  xye
  #xsok
  xpenguins
  #xmoto
  xbubble
  xbomb
  xboing
  #vodovod
  #toppler
  #qonk
  pipewalker
  pipenightdreams
  #mirrormagic
  #minetest
  magicor
  #laby
  holotz-castle
  #hex-a-hop
  #groundhog
  #gsoko
  #gpe-lights
  #frozen-bubble
  attal
  #kiki-the-nano-bot
  xsok
  #rocksndiamonds

  freecraft 
  "freegish"
  glob2 pingus pioneers stax qonk thrust widelands
)

# see equives file
