#!/bin/bash

#pre-install
packages=(
  build-essential
  erlang-base-hipe
  erlang-dev
  erlang-manpages
  erlang-eunit
  erlang-nox
  libicu-dev
  libmozjs185-dev
  libcurl4-openssl-dev
)

aptitude install  "${packages[@]}"

adduser --system \
        --home /usr/local/var/lib/couchdb \
        --no-create-home \
        --shell /bin/bash \
        --group --gecos \
        "CouchDB Administrator" couchdb

##now build and install
#

