#!/bin/bash

packages=(
  build-essential
  erlang-base-hipe
  erlang-dev
  erlang-manpages
  erlang-eunit
  erlang-nox
  libicu-dev
  libmozjs185-dev
  libcurl4-openssl-dev
)

aptitude install  "${packages[@]}"
