#!/bin/bash

export AUGEAS_ROOT=/home/richard/+Files/workshops/system/install/tmp
aliasName=CPUFREQ
cmd1="/usr/bin/cpufreq-set -u 500"
cmd2="/usr/bin/cpufreq-set -u 2000"

augtool -b -s "
    context /files/etc/sudoers.d/cpufreq
    set Cmnd_Alias[alias/name = '$aliasName']/alias/name $aliasName
    set Cmnd_Alias[alias/name = '$aliasName']/alias/command[1] '$cmd1'
    set Cmnd_Alias[alias/name = '$aliasName']/alias/command[2] '$cmd2'
"




#set "$file"'/*[ipaddr="127.0.0.1"]/alias[.="mycouchdb"]' 'mycouchdb'
#set "$file"'/*[ipaddr = "127.0.0.1"]/alias[last()+1]' mycouchdb
