#!/bin/bash

export AUGEAS_ROOT=/home/richard/+Files/workshops/system/install/tmp
aliasName=CPUFREQ

augtool -b -s "
    context /files/etc/sudoers.d/cpufreq
    set Cmnd_Alias[alias/name = 'CPUFREQ']/alias/name CPUFREQ
    set Cmnd_Alias[alias/name = 'CPUFREQ']/alias/command[1] '/usr/bin/cpufreq-set -u 500'
    set Cmnd_Alias[alias/name = 'CPUFREQ']/alias/command[2] '/usr/bin/cpufreq-set -u 2000'
"




#set "$file"'/*[ipaddr="127.0.0.1"]/alias[.="mycouchdb"]' 'mycouchdb'
#set "$file"'/*[ipaddr = "127.0.0.1"]/alias[last()+1]' mycouchdb
