#!/bin/bash

aliasName=CPUFREQ
cmd1="/usr/bin/cpufreq-set -u 500"
cmd2="/usr/bin/cpufreq-set -u 2000"
user="richard"


augtool -b "
    context /files/etc/sudoers.d/cpufreq

    defnode alias Cmnd_Alias[alias/name = '$aliasName']/alias
    set \$alias/name $aliasName
    set \$alias/command[1] '$cmd1'
    set \$alias/command[2] '$cmd2'

    defnode specBase spec[user = '$user']
    defnode user \$specBase/user
    defnode host \$specBase/host_group/host
    defnode command \$specBase/host_group/command
    set \$user $user
    set \$host ALL
    set \$command $aliasName
    set \$command/runas_user root
    set \$command/tag NOPASSWD

    save
"




#set "$file"'/*[ipaddr="127.0.0.1"]/alias[.="mycouchdb"]' 'mycouchdb'
#set "$file"'/*[ipaddr = "127.0.0.1"]/alias[last()+1]' mycouchdb
