#!/bin/bash

if [ "$#" -eq 0 ]
then
    ln -fs -t . src/*
    make my-packages_1.0_all.install
else
    for p in "$@"
    do
        package="$(basename -s .equivs-control "$(basename -s .install "$p")").install"
        make "$package"
    done
fi
