#!/bin/bash

cat >/usr/share/X11/xorg.conf.d/10-my-disable-yoga-keyboard.conf <<- EOF
	Section "InputClass"
	    Identifier "BrokenKeyboard"
	    MatchDevicePath "/dev/input/by-path/platform-i8042-serio-0-event-kbd"
	    Option "Ignore" "true"
	EndSection
EOF
