#!/bin/bash

#augeas is being junk, it will not work with runas_group, it successfully read a sudoers file, but wont write one.

aliasName=DOCKER
file=docker
cmd1="/usr/bin/docker"
user="richard"
run_as="docker"


augtool -b "
    context /files/etc/sudoers.d/$file

    defnode alias Cmnd_Alias[alias/name = '$aliasName']/alias
    set \$alias/name $aliasName
    set \$alias/command[1] '$cmd1'

    defnode specBase spec[user = '$user']
    defnode user \$specBase/user
    defnode host \$specBase/host_group/host
    defnode command \$specBase/host_group/command
    set \$user $user
    set \$host ALL
    set \$command $aliasName
    set \$command/runas_group $run_as
    set \$command/tag NOPASSWD

    save
"




#set "$file"'/*[ipaddr="127.0.0.1"]/alias[.="mycouchdb"]' 'mycouchdb'
#set "$file"'/*[ipaddr = "127.0.0.1"]/alias[last()+1]' mycouchdb
